function result = compute_target_response(radar_signal,radar_platform,target_platform)
%COMPUTE_TARGET_RESPONSE Computes the reflected signal
% Currently does not account for target RCS
    target_slant_range = compute_target_slant_range(radar_platform.altitude,...
        target_platform.altitude,target_platform.range);
    target_doppler = compute_target_doppler(radar_signal.waveform.frequency,...
        radar_platform.velocity,target_platform.velocity);
    target_phase = compute_target_phase_for_each_pulse(radar_signal.waveform,...
        target_slant_range,target_doppler);
    time_shifted_signal = compute_time_shifted_signal(target_slant_range,...
        radar_signal);
    
    result = zeros(radar_signal.waveform.num_pulses,...
        radar_signal.waveform.num_fast_time_samples);
    result = result + target_phase*time_shifted_signal;
    result = blank_receiver_during_transmit(result,...
        get_samples_during_pulse(radar_signal.waveform.num_fast_time_samples,...
            radar_signal.waveform.duty_factor));
end

