
waveform = struct('frequency', 1.0e9,...
                  'pulse_repetition_frequency', 50e3,...
                  'duty_factor', 0.1,...
                  'num_pulses', 64,...
                  'num_fast_time_samples', 1000,...
                  'bandwidth', 5e6,...
                  'starting_phase', 0,...
                  'chirp_direction', +1);
radar_signal = create_signal(waveform);

