%% Test rad_create_range_doppler_map
waveform = struct('frequency', 1.0e9,...
                  'pulse_repetition_frequency', 50e3,...
                  'duty_factor', 0.1,...
                  'num_pulses', 64,...
                  'num_fast_time_samples', 1000,...
                  'bandwidth', 5e6,...
                  'starting_phase', 0,...
                  'chirp_direction', +1);
radar_platform = struct('altitude',9144,...
                        'velocity',300);
target_platform = struct('range',2100,...
                         'altitude',9144,...
                         'velocity',-1575,...
                         'rcs',100);

range_doppler_map = rad_create_range_doppler_map(waveform,radar_platform,...
    target_platform);

load gold_standard_range_doppler_map.mat

delta_rd = range_doppler_map - RD;

imagesc(delta_rd)

assert(all(all(delta_rd == 0)))