function result = rad_create_range_doppler_map(waveform,radar_platform,target_platform)
%RAD_CREATE_RANGE_DOPPLER_MAP Create a range-Doppler map
%   
%
    
    radar_signal = create_signal(waveform);
    target_response = compute_target_response(radar_signal,radar_platform,target_platform);
    matched_filter_signal = compute_matched_filter_signal(radar_signal,target_response);
    doppler_processed_signal = compute_doppler_processed_signal(radar_signal,matched_filter_signal);
    normalized_doppler_signal = normalize_doppler_processed_signal(doppler_processed_signal);
    noisy_range_doppler_map = add_receiver_noise(normalized_doppler_signal);
    
    result = noisy_range_doppler_map;
    
end

% 
% waveform = struct('frequency', 1.0e9,...
%                   'pulse_repetition_frequency', 50e3,...
%                   'duty_factor', 0.1,...
%                   'num_pulses', 64,...
%                   'num_fast_time_samples', 1000,...
%                   'bandwidth', 5e6,...
%                   'starting_phase', 0,...
%                   'chirp_direction', +1);
% radar_platform = struct('altitude',9144,...
%                         'velocity',300);
% target_platform = struct('range',10000,...
%                          'altitude',9144,...
%                          'velocity',-300,...
%                          'rcs',100);
