waveform = struct('frequency', 1.0e9,...
                  'pulse_repetition_frequency', 50e3,...
                  'duty_factor', 0.1,...
                  'num_pulses', 64,...
                  'num_fast_time_samples', 1000,...
                  'bandwidth', 5e6,...
                  'starting_phase', 0,...
                  'chirp_direction', +1);
radar_platform = struct('altitude',9144,...
                        'velocity',300);
target_platform = struct('range',2100,...
                         'altitude',9144,...
                         'velocity',-1575,...
                         'rcs',100);
detector_params = struct('num_training_cells',6,'num_guard_cells',3,...
    'cluster_distance_threshold',0.5);

detected_targets = radsim(waveform,radar_platform,target_platform,detector_params);